# Generated by Django 3.2.4 on 2023-09-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_cart_pw'),
    ]

    operations = [
        migrations.CreateModel(
            name='myorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.ImageField(null=True, upload_to='')),
                ('price', models.IntegerField(null=True)),
                ('tatal_price', models.IntegerField(null=True)),
                ('product_picture', models.CharField(max_length=200, null=True)),
                ('pw', models.CharField(max_length=200, null=True)),
                ('order_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
