# Generated by Django 3.2.4 on 2023-09-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_myorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myorders',
            new_name='okorders',
        ),
    ]
