# Generated by Django 3.2.4 on 2023-09-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_myorders_okorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='okorders',
            new_name='myorders',
        ),
    ]
