# Generated by Django 3.2.4 on 2023-09-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_okorders_myorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tatal_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_picture',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
