# Generated by Django 3.2.4 on 2023-09-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_cart_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myorders',
            old_name='tatal_price',
            new_name='total_price',
        ),
    ]
